config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login' => 'sessions#new', :as => :login
  get '/auth/:provider/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy', :as => :logout
  get '/auth/failure' => 'sessions#failure'

  resources :users, param: :username, path: '/', only: [:show] do
    member do
      get :repos
      get :commits
      get :update_commits
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.username = auth['info']['nickname']
         user.email = auth['info']['email']
         user.avatar_url = auth['info']['image'] || ""
         user.oauth_token = auth['credentials']['token']
      end
    end
  end

  def to_param
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private

  def current_user
    begin
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue Exception => e
      nil
    end
  end

  def user_signed_in?
    return true if current_user
  end

  def correct_user?
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to root_url, :alert => "Access denied."
    end
  end

  def authenticate_user!
    if !current_user
      redirect_to root_url, :alert => 'You need to sign in for access to this page.'
    end
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def render_error
      @exception = env["action_dispatch.exception"]
      @status_code = ActionDispatch::ExceptionWrapper.new(env, @exception).status_code
      render :error_page, status: @status_code, layout: true
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/github'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    reset_session
    session[:user_id] = user.id
    redirect_to repos_user_url(user), :notice => 'Successfully Logged in!'
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Successfully Log out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def repos
     res = RestClient.get("https://api.github.com/users/#{current_user.username}/repos")
     @repos = JSON.parse(res.body)
  end

  def commits
     if request.xhr?
       logger.info "Github commits api : https://api.github.com/repos/#{current_user.username}/#{params[:repo][:name]}/commits?since=#{params[:since].to_s}&until=#{params[:until].to_s}"
       res = RestClient.get("https://api.github.com/repos/#{current_user.username}/#{params[:repo][:name]}/commits?since=#{params[:since]}&until=#{params[:until]}")
     else
       logger.info "Github commits api : https://api.github.com/repos/#{current_user.username}/#{params[:repo][:name]}/commits?until='#{Time.now.utc.iso8601}'"
       res = RestClient.get("https://api.github.com/repos/#{current_user.username}/#{params[:repo][:name]}/commits")
     end

     @commits = JSON.parse(res.body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!-- Header -->
<header class="masthead bg-primary text-white text-center">
  <div class="container">
    <%= image_tag "/assets/profile.png", class: "img-fluid mb-5 d-block mx-auto" %>
    <h1 class="text-uppercase mb-0">Start Github</h1>
    <hr class="star-light">
    <h2 class="font-weight-light mb-0">Web Developer - Graphic Artist - User Experience Designer</h2>
  </div>
</header>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="footer text-center">
  <div class="container">
    <div class="row">
      <div class="col-md-4 mb-5 mb-lg-0">
        <h4 class="text-uppercase mb-4">Location</h4>
        <p class="lead mb-0">Dave Drive
          <br>Pune, MH 411000</p>
      </div>
      <div class="col-md-4 mb-5 mb-lg-0">
        <h4 class="text-uppercase mb-4">Around the Web</h4>
        <ul class="list-inline mb-0">
          <li class="list-inline-item">
            <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
              <i class="fab fa-facebook"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
              <i class="fab fa-google-plus"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
              <i class="fab fa-twitter"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
              <i class="fab fa-linkedin"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
              <i class="fab fa-github"></i>
            </a>
          </li>
        </ul>
      </div>
      <div class="col-md-4">
        <h4 class="text-uppercase mb-4">About Start Github</h4>
        <p class="lead mb-0">Start Github is a free to use, open source tool created by
          <a href="/">Start Github</a>.</p>
      </div>
    </div>
  </div>
</footer>

<div class="copyright py-4 text-center text-white">
  <div class="container">
    <small>Copyright &copy; Start Github 2018</small>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'My Github Repos', repos_user_path(current_user) %></li>
  <li><%= link_to 'Logout', logout_path %></li>
<% else %>
  <li><%= link_to 'Login', login_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
  <div class="container">
    <a class="navbar-brand" href="#page-top">Start Github</a>

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="nav navbar-nav ml-auto pull-right">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Home', root_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Github Auth Example App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Github Auth Example App" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.0.1/d3.v3.min.js"></script>
    <%= csrf_meta_tags %>
  </head>
  <body id="page-top">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div class="container" style="margin-bottom: 20px;">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/errors.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Error!</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <main role="main">
      <div id="wrap row" style="text-align: center; margin: 0 10px;">
        <h1>Error!</h1>

        <div class="content">
          <hr>
          <h2><%= yield %></h2>
          <hr>
        </div>

        <pre>
          <code><%= @exception.inspect %></code>
        </pre>
      </div>
    </main>

  </body>
</html>

app/views/users/_commits_graph.html.erb
<div id='graph-wrapper'></div>

<script type="text/javascript">
  $(document).ready(function(){
    var commits = <%= raw @commits.to_json %>,
    margin = {top: 20, right: 20, bottom: 70, left: 40},
    w = $(document).width() - 165 - margin.left - margin.right,
    h = 600 - margin.top - margin.bottom,
    repoName = $('.commits-graph').attr('id'),
    inputDateDomain = dateDomain(commits),
    commitsByFrequency = commitFrequencies(commits),
    outputCommitDomain = [0, maxCommitsInDay(commitsByFrequency)],
    barWidth = w/daysBetween(inputDateDomain);

    var x = d3.scale.ordinal().rangeRoundBands([0, w], .05);
    var y = d3.scale.linear().range([h, 0]);

    var xAxis = d3.svg.axis()
        .scale(x)
        .orient("bottom")
        .tickFormat(d3.time.format("%Y-%m-%d"));

    var yAxis = d3.svg.axis()
        .scale(y)
        .orient("left")
        .ticks(10);

    var svg = d3.select("#graph-wrapper")
              .append("svg")
              .attr('id', 'graph-canvas')
              .attr("width", w + margin.left + margin.right)
              .attr("height", h + margin.top + margin.bottom)
              .append("g")
                .attr("transform",
                      "translate(" + margin.left + "," + margin.top + ")");

    var barHeight = d3.scale.linear()
    .domain(outputCommitDomain)
    .range([0, h]);

    // this gives us an output from 0 to one less than the number
    // of days from first to last commit, this ensures scale
    // starting at zero, but with correct number of indecies
    var barIndex = d3.time.scale()
    .domain(inputDateDomain)
    .range([0, daysBetween(inputDateDomain) - 1]);

    // map bar indecies to x positions
    var barPosition = d3.scale.linear()
    .domain([0, daysBetween(inputDateDomain)])
    .range([0, w]);

    x.domain(inputDateDomain);
    y.domain([0, d3.max(outputCommitDomain)]);

    svg.append("g")
      .attr("class", "x axis")
      .attr("transform", "translate(0," + h + ")")
      .call(xAxis)
    .selectAll("text")
      .style("text-anchor", "end")
      .attr("dx", "-.8em")
      .attr("dy", "-.55em")
      .attr("transform", "rotate(-90)" );

  svg.append("g")
      .attr("class", "y axis")
      .call(yAxis)
    .append("text")
      .attr("transform", "rotate(-90)")
      .attr("y", 6)
      .attr("dy", ".71em")
      .style("text-anchor", "end")
      .text("Commits");

    svg.selectAll('rect')
    .data(commitsByFrequency)
      .enter()
      .append('rect')
      .style("fill", "steelblue")
      .attr('width',barWidth)
      .attr('height', function(data, index){
      return barHeight(data.length);
      })
      .attr('x', function(data, index){
      var date = commitDate(data[0]),
          index = barIndex(date),
          pos = barPosition(index);
      return pos;
      })
      .attr('y', function(data, index){
      return h - barHeight(data.length);
      })
      .on('mouseenter', function(data){
      $("#bar-info").html(data.length + " Commits on " + commitDate(data[0]));
      });

  });
</script>

app/views/users/commits.html.erb
<div class="row">
  <div class="col-lg-12 mx-auto">
    <h2 class="text-secondary text-uppercase mb-0"><%= params[:repo][:name] %></h2>
    <hr class="star-dark mb-5">
    <img class="img-fluid mb-5" src="/assets/github-icon.png" alt="" style="width: 15%; float: left;">
    <p class="mb-5 clearfix">
      <%= params[:repo][:description] %><br>
      Created: <%= Date.parse(params[:repo][:created_at]).strftime("%b %d, %Y") %><br>
      Size: <%= params[:repo][:size] %> bytes <br>
      Main Language: <%= params[:repo][:language] %>
    </p>

    <div id='header-wrapper mb-5'>
      <h2 class="text-secondary text-center" id="title"> Commits on <span>Github</span> Repository </h1>
        <div class="md-form">
          <input placeholder="Selected date" type="text" class="daterange form-control">
      </div>
    </div>

    <div class="commits-graph" id="<%= params[:repo][:name] %>"><%= render 'commits_graph' %></div>

    <h2 id='bar-info' class="text-center"></h2>
  </div>
</div>

<script type="text/javascript">
$(document).ready(function() {
  var commits = <%= raw @commits.to_json %>,
  repoName = $('.commits-graph').attr('id');
  $('.daterange').daterangepicker(
    {
      locale: {
        format: 'YYYY-MM-DD'
      },
      startDate: dateDomain(commits)[0],
      endDate: dateDomain(commits)[1]
    },
    function(start, end, label) {

        // alert("A new date range was chosen: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
        $.ajax({
          type: "GET",
          contentType: "application/json",
          url: "commits",
          data: { since: String(start), until: String(end), repo: {name: String(repoName)} },
          dataType: "script",
          beforeSend: function() {
            $(".commits-graph").addClass('loadingDiv');
          },
          success: function (result) {
              $(".commits-graph").removeClass('loadingDiv');
           },
           error: function (){
              window.alert("something wrong!");
           }
        });
    });

});
</script>

app/views/users/commits.js.erb
$(".commits-graph").html("<%= escape_javascript(render partial: "commits_graph", locals: {commits: @commits}) %>");

app/views/users/repos.html.erb
<div class="row">
  <h2 class="text-center text-uppercase text-secondary mb-0">My Repositories (<%= @repos.size %>)</h2>
  <hr class="star-dark mb-5">

  <% @repos.each_with_index do |repo, index| %>
    <div class="col-md-6 col-lg-3 text-center text-uppercase" id="d1">
      <a class="portfolio-item d-block mx-auto" href="<%= commits_user_url(repo: repo.slice('name', 'description', 'html_url', 'size', 'created_at', 'language')) %>">
        <%= image_tag("/assets/github-icon.png", class: "img-fluid", style: "width: 50%;") %>
        <h3 style="margin-top: 0;"><%= repo['name'].truncate(20) %></h3>
      </a>
    </div>
  <% end %>
</div>